# Generated by Django 5.2 on 2025-04-23 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("amazonbrands", "0004_remove_product_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="brand",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_query_name="brand",
                to="amazonbrands.brand",
            ),
        ),
    ]
